server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - TokenRelay
        - AddResponseHeader=X-Gateway, Grupo114

      routes:
        ## ================================
        ## MS-USUARIOS
        ## ================================
        - id: ms-usuarios
          uri: http://ms-usuarios:8080
          predicates:
            - Path=/api/usuarios/**,/api/clientes/**,/api/transportistas/**

        ## ================================
        ## MS-TARIFAS
        ## ================================
        - id: ms-tarifas
          uri: http://ms-tarifas:8080
          predicates:
            - Path=/api/tarifas/**

        ## ================================
        ## MS-CAMIONES
        ## ================================
        - id: ms-camiones
          uri: http://ms-camiones:8080
          predicates:
            - Path=/api/camiones/**,
                    /api/depositos/**,
                    /api/tipos-camion,
                    /api/tipos-camion/**

        ## ================================
        ## MS-SOLICITUDES
        ## ================================
        - id: ms-solicitudes
          uri: http://ms-solicitudes:8080
          predicates:
            - Path=/api/solicitudes/**,/api/tramos/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tpi-backend
          jwk-set-uri: http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
